# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-10 20:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 10, 20, 25, 41, 922601, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='answer',
            name='text',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 10, 20, 25, 41, 921689, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='question',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
