# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-10 20:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20160310_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 10, 20, 35, 29, 453152, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 10, 20, 35, 29, 452326, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
